### your site title here

baseurl: "" #name of GitHub repository
url: "bastoica.github.io" #custom url to be used instead of GitHub repository

title: Bogdan "Bo" Alexandru Stoica
title_short: B. A. Stoica
description: Postdoctoral Research Associate, SysNet @ UIUC
useful_links: <a class="useful-links" target="_blank" href="/files/metadata/bogdan_stoica_cv.pdf">CV</a> / <a class="useful-links" target="_blank" href="https://github.com/bastoica">GitHub</a> / <a class="useful-links" target="_blank" rel="me" href="https://bsky.app/profile/cachemisses.bsky.social">BlueSky</a> / <a class="useful-links" target="_blank" rel="me" href="https://discuss.systems/@CacheMisses">Mastodon</a> / <a class="useful-links" target="_blank" href="https://twitter.com/CacheMisses">Twitter</a>
contact: "Contact: bastoica-AT-illinois-DOT-edu"
email: #

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
twitter: "#"
linkedin: "#"
stackoverflow: "#"
github: "#"
researchgate: "#"
orcid: "#"
quora: "#"
instagram: "#"
facebook: "#"


# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - shortProject.md
      - longerProjectTitle.md
      - redirect.md
      - project4.md
      - project5.md
      - project6.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md
  - vendor
  - bundle

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
